### ISSUE TITLE
USER STEALS 

### ISSUE THREAD

**Issue by SleepTheGod** [cvs0/DiscordClone#2]
GIVE THEM CREDIT BOZO OR WE WILL COME TO YOUR HOUSE AND TAKE YOUR HDD

**Comment by SleepTheGod** [comment]
USER HITS ON 11 YEAR OLD BOYS

**Comment by SleepTheGod** [comment]
pm2 start new bank account loan

**Comment by cvs0** [comment]
LOL who is this guy

**Comment by cvs0** [comment]
Give who credit smoothbrain
